### ISSUE TITLE
Issue with running the project locally

### ISSUE THREAD

**Issue by oskarmartin** [SrMoffat/wer1-backend#14]
Heya

I have looked over the code that you provided for the test assignment and overall the code side looks nice and seems that there are no mistakes there. 
Unfortunately when I try to run the project locally on my machine with `docker-compose up --build` I get this error. Do you by any chance know how could I fix this or what should I do to get this project running on my local machine.

<img width="1717" alt="image" src="https://github.com/SrMoffat/wer1-backend/assets/21955292/849bb6d6-7a4f-4206-b23c-ede4c6a2e713">

**Comment by oskarmartin** [comment]
@SrMoffat Thanks for the quick answer, let me know in this thread when you have found a solution for that.
Will be looking forward to it!

**Comment by SrMoffat** [comment]
Hi @oskarmartin,

I found several issues that I'm working on fixing:

1. The setup does not include a step to export all the required environment variables used in the `docker-compose`so we get:
```bash
WARNING: The `POSTGRES_USER` variable is not set. Defaulting to a blank string.
WARNING: The `POSTGRES_PASSWORD` variable is not set. Defaulting to a blank string.
WARNING: The `POSTGRES_DB` variable is not set. Defaulting to a blank string.
```
2. The setup also uses `yarn` which seems to not find the `node` binary to use so we get:
```bash
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1689731296824-0.5232803909677024/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
```
3. The `api` fails to build because the Typescript compiler `tsc` seems to be missing something when using `Nexus` for types. I'm not sure why this happens but some people propose downgrading Typescript solves it so I'll try it. That's why we get:
```bash
nexus-typegen.ts(7,15): error TS2724: ‘“./src/context”’ has no exported member named ‘Context’. Did you mean ‘context’?
#11 20.09 node_modules/.prisma/client/index.d.ts(1078,18): error TS2344: Type ‘GlobalRejectSettings’ does not satisfy the constraint ‘RejectOnNotFound | RejectPerOperation | undefined’.
#11 20.09   Type ‘GlobalRejectSettings’ is not assignable to type ‘RejectPerOperation’.
#11 20.09 node_modules/.prisma/client/index.d.ts(1095,18): error TS2344: Type ‘GlobalRejectSettings’ does not satisfy the constraint ‘RejectOnNotFound | RejectPerOperation | undefined’.
#11 20.09 node_modules/.prisma/client/index.d.ts(1919,18): error TS2344: Type ‘GlobalRejectSettings’ does not satisfy the constraint ‘RejectOnNotFound | RejectPerOperation | undefined’.
#11 20.09   Type ‘GlobalRejectSettings’ is not assignable to type ‘RejectPerOperation’.
#11 20.09 node_modules/.prisma/client/index.d.ts(1936,18): error TS2344: Type ‘GlobalRejectSettings’ does not satisfy the constraint ‘RejectOnNotFound | RejectPerOperation | undefined’.
#11 20.09 node_modules/nexus/dist/plugin.d.ts(114,123): error TS2707: Generic type ‘GraphQLFieldResolver’ requires between 2 and 3 type arguments.
#11 20.09 node_modules/nexus/dist/utils.d.ts(80,43): error TS2315: Type ‘GraphQLScalarType’ is not generic.
```

I'm working on fixes for this, I'll let you know when the pull request is up for fixes. Thanks for your patience. I will also include setup steps for local development as I fix the issue with production build.
